DROP TABLE IF EXISTS API_PATTERN;
create table API_PATTERN(PATTERN VARCHAR(255) default NULL, AUTHORITIES VARCHAR(255) default NULL);
DROP TABLE IF EXISTS API_KEY;
create table API_KEY (KEY VARCHAR(255) NOT NULL, AUTHORITIES VARCHAR(255), ENABLED BOOLEAN(1), EXPIRED BOOLEAN(1), LOCKED BOOLEAN(1));